name: Yhorm Dark Souls
source: https://imgflip.com/meme/171457391/Yhorm-Dark-Souls
keywords:
  - yhorm the giant
  - ashen one
  - dark souls
  - giant vs small
  - boss fight
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.28
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.6
    scale_y: 0.35
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.09
    anchor_y: 0.65
    angle: 0.0
    scale_x: 0.36
    scale_y: 0.24
    align: center
    start: 0.0
    stop: 1.0
example:
  - A massive task
  - Me
