name: Lord of the Rings Meat's back on the menu
source: https://imgflip.com/meme/35118549/Lord-of-the-Rings-Meats-back-on-the-menu
keywords:
  - lord of the rings
  - meat's back on the menu
  - orc
  - uruk-hai
  - looks like
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.005
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.245
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.75
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.23
    align: center
    start: 0.0
    stop: 1.0
example:
  - When the server comes back online
  - "Looks like meat's back on the menu, boys!"
