name: Roll Safe Think About It
source: https://imgflip.com/memetemplate/89370399
keywords:
  - roll safe
  - think about it
  - smart guy
  - pointing to head
  - kayode ewumi
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.002
    angle: 0.0
    scale_x: 0.978
    scale_y: 0.198
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.8
    angle: 0.0
    scale_x: 0.978
    scale_y: 0.195
    align: center
    start: 0.0
    stop: 1.0
example:
  - YOU CAN'T BE LATE TO WORK
  - IF YOU DON'T HAVE A JOB
