name: Laughing Wolf
source: https://imgflip.com/meme/254336433/Laughing-wolf
keywords:
  - laughing wolf
  - three wolves
  - two laughing wolves
  - annoyed wolf
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.02
    anchor_y: 0.35
    angle: 0.0
    scale_x: 0.26
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.38
    anchor_y: 0.25
    angle: 0.0
    scale_x: 0.2
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.7
    anchor_y: 0.45
    angle: 0.0
    scale_x: 0.25
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - Me making a bad joke
  - My annoyed friend
  - My other friend laughing
