name: Sun Tzu
source: https://imgflip.com/meme/84898556/Sun-Tzu
keywords:
  - sun tzu
  - art of war
  - quote
  - fake quote
  - statue
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.3
    anchor_y: 0.15
    angle: 0.0
    scale_x: 0.65
    scale_y: 0.7
    align: left
    start: 0.0
    stop: 1.0
example:
  - "\"If you are bad at a game, just win.\"\n- Sun Tzu, The Art of War"
