name: Elmo Rise
source: https://imgflip.com/meme/205604035/Dancin-bois
keywords:
  - elmo
  - fire
  - hell
  - burn
  - chaos
  - dancin bois
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.005
    anchor_y: 0.005
    angle: 0.0
    scale_x: 0.99
    scale_y: 0.195
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.005
    anchor_y: 0.8
    angle: 0.0
    scale_x: 0.99
    scale_y: 0.19
    align: center
    start: 0.0
    stop: 1.0
example:
  - ME WATCHING THE DRAMA UNFOLD
  - THAT I CREATED
