name: Corporate wants you to find the difference
source: https://imgflip.com/meme/177915752/corporate-wants-you-to-find-the-difference
keywords:
  - the office
  - pam
  - corporate needs you to find the differences
  - they're the same picture
text:
  - style: upper
    color: black
    font: thick
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.3
    scale_y: 0.18
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: black
    font: thick
    anchor_x: 0.55
    anchor_y: 0.15
    angle: 0.0
    scale_x: 0.35
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - First thing
  - Second thing
