name: Jason Momoa Henry Cavill Meme
source: https://imgflip.com/meme/137135579/Jason-Momoa-Henry-Cavill-Meme
keywords:
  - jason momoa
  - henry cavill
  - sneaking up
  - behind
  - surprise attack
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.11
    anchor_y: 0.45
    angle: 0.0
    scale_x: 0.19
    scale_y: 0.11
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.45
    anchor_y: 0.35
    angle: 0.0
    scale_x: 0.4
    scale_y: 0.25
    align: center
    start: 0.0
    stop: 1.0
example:
  - My responsibilities
  - Me enjoying my weekend
