name: Riley Reid Meme
source: https://imgflip.com/meme/219388197/Riley-Reid-meme
keywords:
  - riley reid
  - disgusted
  - face
  - reaction
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.003
    angle: 0.0
    scale_x: 0.978
    scale_y: 0.197
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.8
    angle: 0.0
    scale_x: 0.978
    scale_y: 0.19
    align: center
    start: 0.0
    stop: 1.0
example:
  - When they ask you to work on the weekend
  - But you already have plans to do nothing
