name: Angela scared Dwight
source: https://imgflip.com/meme/165843635/Angela-scared-Dwight
keywords:
  - angela
  - dwight
  - the office
  - scared
  - startled
  - behind
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.2
    anchor_y: 0.25
    angle: 0.0
    scale_x: 0.3
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.66
    anchor_y: 0.3
    angle: 0.0
    scale_x: 0.26
    scale_y: 0.21
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.1
    anchor_y: 0.7
    angle: 0.0
    scale_x: 0.45
    scale_y: 0.28
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.66
    anchor_y: 0.8
    angle: 0.0
    scale_x: 0.29
    scale_y: 0.19
    align: center
    start: 0.0
    stop: 1.0
example:
  - Me enjoying my weekend
  - Monday morning
  - Me
  - Monday morning
