name: Where Monkey
source: https://imgflip.com/memetemplate/316466202
keywords:
  - where monkey
  - where banana
  - orangutans
  - monkeys on couch
  - ape
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.012
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.138
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.85
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.14
    align: center
    start: 0.0
    stop: 1.0
example:
  - where banana
  - where update
