name: Did you do it? Yes. What did it cost? Everything.
source: https://imgflip.com/meme/643383637/speed-crashing-out
keywords:
  - thanos
  - gamora
  - what did it cost
  - everything
  - avengers
  - infinity war
  - four panels
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.38
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.1
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.51
    anchor_y: 0.38
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.1
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.88
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.1
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.51
    anchor_y: 0.88
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.1
    align: center
    start: 0.0
    stop: 1.0
example:
  - Did you do it?
  - Yes.
  - What did it cost?
  - Everything.
