name: Black Box Meme
source: https://imgflip.com/meme/324865299/Black-Box-Meme
keywords:
  - demotivational poster
  - black border
  - demotivational
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.78
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.1
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.1
    anchor_y: 0.88
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.1
    align: center
    start: 0.0
    stop: 1.0
example:
  - TITLE
  - This is the subtitle explaining the title.
