name: Squidward Pointing
source: https://imgflip.com/meme/248110290/Squidward-pointing
keywords:
  - squidward
  - pointing
  - spongebob
  - angry
  - accusing
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.02
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.18
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.8
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.18
    align: center
    start: 0.0
    stop: 1.0
example:
  - WHEN SOMEONE SAYS
  - THEY DON'T LIKE SPONGEBOB
