#!/usr/bin/env python3
"""
Generate a browsable INDEX.md catalog of the templates in extra-templates/.

Scans every template folder, reads its config.yml, and writes a sorted Markdown
table (name, id, panels, keywords, source) plus the meme URL pattern - so the
baked-in extras are easy to find without opening each folder. Re-run any time
templates are added/changed.

Usage:
    python3 build-template-index.py                 # indexes ../extra-templates
    python3 build-template-index.py --dir /some/dir
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEFAULT_DIR = HERE.parent / "extra-templates"


def read_config(cfg: Path) -> dict:
    text = cfg.read_text()
    name = re.search(r"^name:\s*(.+)$", text, re.MULTILINE)
    source = re.search(r"^source:\s*(.+)$", text, re.MULTILINE)
    panels = len(re.findall(r"^  - style:", text, re.MULTILINE))
    kw_block = re.search(r"^keywords:\n((?:\s+-.*\n?)*)", text, re.MULTILINE)
    keywords = []
    if kw_block:
        for line in kw_block.group(1).splitlines():
            k = line.strip().lstrip("-").strip().strip('"')
            if k:
                keywords.append(k)
    return {
        "name": (name.group(1).strip().strip('"') if name else "?"),
        "source": (source.group(1).strip() if source else ""),
        "panels": panels,
        "keywords": keywords,
    }


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dir", type=Path, default=DEFAULT_DIR)
    args = ap.parse_args()

    folders = sorted(d for d in args.dir.iterdir() if d.is_dir())
    rows = []
    for d in folders:
        cfg = d / "config.yml"
        if not cfg.exists():
            continue
        img = next((p.name for p in sorted(d.iterdir()) if p.stem == "default"), "")
        meta = read_config(cfg)
        rows.append((d.name, meta, img))

    rows.sort(key=lambda r: r[1]["name"].lower())

    lines = [
        "# Extra templates index",
        "",
        f"{len(rows)} VLM-marked templates baked into the image on top of memegen's "
        "~200 upstream ones. Use a template by id, e.g. `/images/<id>/top/bottom.png`.",
        "",
        "_Generated by `scripts/build-template-index.py` - do not edit by hand._",
        "",
        "| Name | id | Panels | Keywords | Source |",
        "| --- | --- | :---: | --- | --- |",
    ]
    for slug, meta, _img in rows:
        kw = ", ".join(meta["keywords"][:6])
        src = f"[link]({meta['source']})" if meta["source"].startswith("http") else ""
        lines.append(f"| {meta['name']} | `{slug}` | {meta['panels']} | {kw} | {src} |")
    lines.append("")

    out = args.dir / "INDEX.md"
    out.write_text("\n".join(lines))
    print(f"wrote {out} ({len(rows)} templates)")


if __name__ == "__main__":
    main()
