name: I wish all x a very y
source: https://imgflip.com/meme/298196439/I-wish-all-x-a-very-y
keywords:
  - bugs bunny
  - tuxedo
  - i wish all
  - a very
  - formal
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.03
    anchor_y: 0.18
    angle: 0.0
    scale_x: 0.32
    scale_y: 0.37
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.03
    anchor_y: 0.68
    angle: 0.0
    scale_x: 0.32
    scale_y: 0.27
    align: center
    start: 0.0
    stop: 1.0
example:
  - gamers
  - pleasant evening
