name: "Oops! All Berries"
source: https://imgflip.com/meme/152344231/Oops-All-Berries
keywords:
  - oops all berries
  - cap'n crunch
  - cereal box
  - oops all
text:
  - style: upper
    color: black
    font: thick
    anchor_x: 0.197
    anchor_y: 0.072
    angle: 0.0
    scale_x: 0.45
    scale_y: 0.278
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.128
    anchor_y: 0.4
    angle: 0.0
    scale_x: 0.847
    scale_y: 0.198
    align: center
    start: 0.0
    stop: 1.0
example:
  - My mistakes
  - Berries
