name: Black background
source: https://imgflip.com/meme/18630807/Black-background
keywords:
  - black
  - dark
  - blank
  - solid color
  - simple
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.05
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.4
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.55
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.4
    align: center
    start: 0.0
    stop: 1.0
example:
  - TOP TEXT
  - BOTTOM TEXT
