name: That's a paddlin'
source: https://imgflip.com/meme/Thats-a-paddlin
keywords:
  - jasper
  - simpsons
  - paddlin
  - paddle
  - school
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.015
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.185
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.82
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.16
    align: center
    start: 0.0
    stop: 1.0
example:
  - Looking at my sandals?
  - That's a paddlin'
