name: Sleeping Shaq
source: https://imgflip.com/memetemplate/99683372
keywords:
  - sleeping shaq
  - i sleep
  - real shit
  - shaquille o'neal
  - glowing eyes
text:
  - style: upper
    color: black
    font: thick
    anchor_x: 0.01
    anchor_y: 0.01
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.51
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: black
    font: thick
    anchor_x: 0.01
    anchor_y: 0.545
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.445
    align: center
    start: 0.0
    stop: 1.0
example:
  - Something boring or unimportant
  - Something exciting or urgent
