name: All My Homies Hate
source: https://imgflip.com/memetemplate/216523697
keywords:
  - all my homies hate
  - fuck
  - gang
  - sagging pants
  - homies
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.015
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.135
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.84
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.14
    align: center
    start: 0.0
    stop: 1.0
example:
  - FUCK TIKTOK
  - ALL MY HOMIES HATE TIKTOK
