name: Astronaut Always Has Been
source: https://imgflip.com/meme/255177692/astronaut-meme-always-has-been-template
keywords:
  - astronaut
  - always has been
  - space
  - gun
  - earth
  - ohio
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.15
    anchor_y: 0.25
    angle: 0.0
    scale_x: 0.2
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.38
    anchor_y: 0.45
    angle: 0.0
    scale_x: 0.15
    scale_y: 0.13
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.6
    anchor_y: 0.35
    angle: 0.0
    scale_x: 0.25
    scale_y: 0.13
    align: center
    start: 0.0
    stop: 1.0
example:
  - Ohio
  - "Wait, it's all Ohio?"
  - Always has been.
