name: Not sure if- fry
source: https://imgflip.com/meme/74963439/Not-sure-if--fry
keywords:
  - futurama
  - fry
  - not sure if
  - skeptical
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.02
    anchor_y: 0.02
    angle: 0.0
    scale_x: 0.96
    scale_y: 0.23
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.02
    anchor_y: 0.75
    angle: 0.0
    scale_x: 0.96
    scale_y: 0.23
    align: center
    start: 0.0
    stop: 1.0
example:
  - NOT SURE IF REAL LIFE
  - OR JUST FANTASY
