name: Old man yells at cloud
source: https://imgflip.com/meme/54522231/Old-man-yells-at-cloud
keywords:
  - simpsons
  - abe simpson
  - grandpa simpson
  - yelling
  - cloud
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.003
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.137
    align: center
    start: 0.0
    stop: 1.0
example:
  - OLD MAN YELLS AT CLOUD
