name: Monster House Disappointed
source: https://imgflip.com/meme/647527706/Monster-house-disappointed
keywords:
  - monster house
  - disappointed
  - bones
  - reginald
  - stare
  - disgusted
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.003
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.147
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.85
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.14
    align: center
    start: 0.0
    stop: 1.0
example:
  - When they say they don't like your favorite movie
  - My honest reaction
