name: Drowning Kid and Skeleton
source: https://imgflip.com/meme/252926078/drowning-kid--skeleton
keywords:
  - drowning kid
  - skeleton
  - pool
  - mother ignoring kid
  - underwater
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.435
    anchor_y: 0.168
    angle: 0.0
    scale_x: 0.205
    scale_y: 0.239
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.48
    anchor_y: 0.226
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.215
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.075
    anchor_y: 0.358
    angle: 0.0
    scale_x: 0.3
    scale_y: 0.222
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.41
    anchor_y: 0.69
    angle: 0.0
    scale_x: 0.31
    scale_y: 0.308
    align: center
    start: 0.0
    stop: 1.0
example:
  - The favorite child
  - Mother
  - The drowning kid
  - The forgotten skeleton
