name: First time?
source: https://imgflip.com/meme/277489984/First-time
keywords:
  - first time
  - james franco
  - hanging
  - noose
  - ballad of buster scruggs
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.2
    anchor_y: 0.28
    angle: 0.0
    scale_x: 0.33
    scale_y: 0.21
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.3
    anchor_y: 0.55
    angle: 0.0
    scale_x: 0.45
    scale_y: 0.44
    align: center
    start: 0.0
    stop: 1.0
example:
  - Me crying over a minor inconvenience
  - Experienced person
