name: Bro visited his friend
source: https://imgflip.com/meme/525752147/Bro-visited-his-friend
keywords:
  - bro visited his friend
  - speech bubble
  - drawing
  - comic
text:
  - style: upper
    color: black
    font: thick
    anchor_x: 0.025
    anchor_y: 0.25
    angle: 0.0
    scale_x: 0.205
    scale_y: 0.14
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: black
    font: thick
    anchor_x: 0.22
    anchor_y: 0.25
    angle: 0.0
    scale_x: 0.255
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - bro visited his friend
  - friend was happy to see him
