name: Anthony Adams Rubbing Hands
source: https://imgflip.com/meme/196595107/Anthony-Adams-Rubbing-Hands
keywords:
  - anthony adams
  - rubbing hands
  - behind tree
  - yellow suit
  - waiting
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.3
    angle: 0.0
    scale_x: 0.29
    scale_y: 0.4
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.53
    anchor_y: 0.35
    angle: 0.0
    scale_x: 0.28
    scale_y: 0.47
    align: center
    start: 0.0
    stop: 1.0
example:
  - A brand new video game release
  - Me with 100+ hours of free time
