name: Makima is listening
source: https://imgflip.com/meme/434528469/Makima-is-listening
keywords:
  - chainsaw man
  - kishibe
  - notebook
  - is listening
  - manga
text:
  - style: upper
    color: black
    font: thick
    anchor_x: 0.495
    anchor_y: 0.28
    angle: 0.0
    scale_x: 0.236
    scale_y: 0.21
    align: center
    start: 0.0
    stop: 1.0
example:
  - Makima
