name: That's how you do it
source: https://imgflip.com/meme/321927696/Thats-how-you-do-it
keywords:
  - simpsons
  - that's how you do it
  - father
  - son
  - teaching
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.01
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.11
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.88
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.11
    align: center
    start: 0.0
    stop: 1.0
example:
  - When you show the new hire how to do the job
  - And they actually get it right
