name: Y'all Got Any More Of That
source: https://imgflip.com/memetemplate/124055727
keywords:
  - tyrone biggums
  - dave chappelle
  - y'all got any more of
  - crackhead
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.002
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.148
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.82
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.16
    align: center
    start: 0.0
    stop: 1.0
example:
  - Y'ALL GOT ANY MORE OF THEM
  - PIXELS
