name: "I don't care if you win, I just need X to lose"
source: https://imgflip.com/meme/295089902/I-dont-care-if-you-win-I-just-need-X-to-lose
keywords:
  - general hux
  - star wars
  - i don't care if you win
  - i just need to lose
  - two panels
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.38
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.1
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.88
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.1
    align: center
    start: 0.0
    stop: 1.0
example:
  - I don't care if you win
  - I just need him to lose
