name: No Fear One Fear
source: https://imgflip.com/meme/97506572/No-Fear-One-Fear
keywords:
  - no fear
  - one fear
  - comic
  - t-shirt
text:
  - style: upper
    color: black
    font: thick
    anchor_x: 0.36
    anchor_y: 0.25
    angle: 0.0
    scale_x: 0.275
    scale_y: 0.595
    align: center
    start: 0.0
    stop: 1.0
example:
  - My alarm not going off
