name: A second plane has just hit
source: https://imgflip.com/meme/441974336/A-second-plane-has-just-hit
keywords:
  - george bush
  - whispering
  - sir a second
  - news
  - reaction
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.015
    anchor_y: 0.015
    angle: 0.0
    scale_x: 0.97
    scale_y: 0.135
    align: center
    start: 0.0
    stop: 1.0
example:
  - "Sir, a second post has hit the timeline"
