name: "Silence X, a Y is talking"
source: https://imgflip.com/meme/534143336/Silence-X-a-Y-is-talking
keywords:
  - silence
  - king baldwin
  - kingdom of heaven
  - is talking
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.61
    anchor_y: 0.015
    angle: 0.0
    scale_x: 0.37
    scale_y: 0.095
    align: left
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.12
    anchor_y: 0.9
    angle: 0.0
    scale_x: 0.42
    scale_y: 0.085
    align: center
    start: 0.0
    stop: 1.0
example:
  - liberal
  - centrist
