name: Disappointed Muhammad Sarim Akhtar
source: https://imgflip.com/meme/219458796/Disappointed-Muhammad-Sarim-Akhtar
keywords:
  - disappointed
  - pakistan fan
  - cricket
  - hands on hips
  - annoyed
  - disappointed cricket fan
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.002
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.178
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.82
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.17
    align: center
    start: 0.0
    stop: 1.0
example:
  - WHEN YOU TRY YOUR BEST
  - BUT YOU DON'T SUCCEED
