name: Disappointed Black Guy
source: https://imgflip.com/memetemplate/50421420
keywords:
  - disappointed black guy
  - excited
  - sad
  - disappointed
  - reaction
  - two panels
text:
  - style: upper
    color: black
    font: thick
    anchor_x: 0.01
    anchor_y: 0.01
    angle: 0.0
    scale_x: 0.59
    scale_y: 0.455
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: black
    font: thick
    anchor_x: 0.01
    anchor_y: 0.485
    angle: 0.0
    scale_x: 0.59
    scale_y: 0.5
    align: center
    start: 0.0
    stop: 1.0
example:
  - When you find a great new show to watch
  - It gets cancelled after one season
