name: Swimming Pool Kids
source: https://imgflip.com/meme/256474083/Swimming-Pool-Kids
keywords:
  - swimming pool
  - drowning
  - skeleton
  - mother holding kid
  - neglected
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.435
    anchor_y: 0.151
    angle: 0.0
    scale_x: 0.205
    scale_y: 0.215
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.5
    anchor_y: 0.204
    angle: 0.0
    scale_x: 0.483
    scale_y: 0.191
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.08
    anchor_y: 0.324
    angle: 0.0
    scale_x: 0.3
    scale_y: 0.191
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.34
    anchor_y: 0.614
    angle: 0.0
    scale_x: 0.4
    scale_y: 0.384
    align: center
    start: 0.0
    stop: 1.0
example:
  - My favorite project
  - Me
  - My other projects
  - My health and sleep schedule
