name: Bugs Bunny Communist
source: https://imgflip.com/memetemplate/249257686
keywords:
  - bugs bunny
  - communist
  - our
  - hammer and sickle
  - soviet union
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.005
    angle: 0.0
    scale_x: 0.978
    scale_y: 0.145
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.35
    anchor_y: 0.82
    angle: 0.0
    scale_x: 0.63
    scale_y: 0.16
    align: center
    start: 0.0
    stop: 1.0
example:
  - My mom buys food
  - Our food
