name: Bilbo - Why shouldn't I keep it?
source: https://imgflip.com/meme/256635436/Bilbo---Why-shouldnt-I-keep-it
keywords:
  - bilbo
  - lord of the rings
  - why shouldn't i keep it
  - after all why not
  - two panels
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.015
    anchor_y: 0.015
    angle: 0.0
    scale_x: 0.969
    scale_y: 0.105
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.015
    anchor_y: 0.88
    angle: 0.0
    scale_x: 0.969
    scale_y: 0.105
    align: center
    start: 0.0
    stop: 1.0
example:
  - Me looking at the last slice of pizza
  - "After all, why not? Why shouldn't I eat it?"
