name: Jarvis Template
source: https://imgflip.com/meme/568618654/Jarvis-Template
keywords:
  - jarvis
  - tony stark
  - iron man
  - hud
  - marvel
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.002
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.148
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.85
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.14
    align: center
    start: 0.0
    stop: 1.0
example:
  - "JARVIS, FIND OUT"
  - WHO ASKED
