name: Feel like pure shit
source: https://imgflip.com/meme/129577132/Feel-like-pure-shit
keywords:
  - crying
  - sad
  - feel like pure shit just want her back x
  - boy crying
  - tear
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.005
    anchor_y: 0.003
    angle: 0.0
    scale_x: 0.99
    scale_y: 0.147
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.005
    anchor_y: 0.85
    angle: 0.0
    scale_x: 0.99
    scale_y: 0.14
    align: center
    start: 0.0
    stop: 1.0
example:
  - feel like pure shit
  - just want her back x
