name: Drake Hotline Bling
source: https://imgflip.com/memetemplate/181913649
keywords:
  - drake
  - hotline bling
  - no
  - yes
  - dislike
  - like
  - prefer
text:
  - style: upper
    color: black
    font: thick
    anchor_x: 0.52
    anchor_y: 0.02
    angle: 0.0
    scale_x: 0.46
    scale_y: 0.46
    align: left
    start: 0.0
    stop: 1.0
  - style: upper
    color: black
    font: thick
    anchor_x: 0.52
    anchor_y: 0.52
    angle: 0.0
    scale_x: 0.46
    scale_y: 0.46
    align: left
    start: 0.0
    stop: 1.0
example:
  - Using a pre-made library
  - Writing it from scratch yourself
