name: "Say it Again, Dexter"
source: https://imgflip.com/meme/Say-it-Again-Dexter
keywords:
  - dexter's laboratory
  - say it again
  - omelette du fromage
  - whisper
  - girls
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.015
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.135
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.84
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.145
    align: center
    start: 0.0
    stop: 1.0
example:
  - "Say it again, Dexter"
  - Omelette du fromage
