name: Megamind No Bitches
source: https://imgflip.com/memetemplate/371619279
keywords:
  - megamind
  - no bitches
  - no
  - bitches
  - close up
  - stare
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.005
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.195
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.8
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.19
    align: center
    start: 0.0
    stop: 1.0
example:
  - NO BITCHES?
  - NO BITCHES?
