name: Mocking Spongebob
source: https://imgflip.com/meme/102723630/triggerpaul
keywords:
  - spongebob
  - mocking
  - sarcastic
  - chicken
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.002
    angle: 0.0
    scale_x: 0.978
    scale_y: 0.118
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.88
    angle: 0.0
    scale_x: 0.978
    scale_y: 0.11
    align: center
    start: 0.0
    stop: 1.0
example:
  - mE sTaRtInG a NeW dIeT
  - Me StArTiNg A nEw DiEt
