name: 20 Minute Adventure Rick and Morty
source: https://imgflip.com/meme/205214210/20-minute-adventure-rick-morty
keywords:
  - rick and morty
  - 20 minute adventure
  - in and out
  - crying
  - regret
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.01
    angle: 0.0
    scale_x: 0.35
    scale_y: 0.07
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.475
    angle: 0.0
    scale_x: 0.35
    scale_y: 0.07
    align: center
    start: 0.0
    stop: 1.0
example:
  - Me starting a quick side project
  - Me 12 hours later
