name: Society If
source: https://imgflip.com/meme/180046896/society-if
keywords:
  - society if
  - futuristic city
  - utopia
  - future
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.003
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.147
    align: center
    start: 0.0
    stop: 1.0
example:
  - Society if people used the correct meme templates
