name: Badass Skeleton
source: https://imgflip.com/meme/143031762/Badass-Skeleton
keywords:
  - skeleton
  - gun
  - grim reaper
  - badass
  - skull
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.02
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.13
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.85
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.13
    align: center
    start: 0.0
    stop: 1.0
example:
  - WHEN YOU ASK FOR NO PICKLES
  - AND THEY GIVE YOU PICKLES
