name: The Circle of Life
source: https://imgflip.com/meme/73012190/the-circle-of-life
keywords:
  - lion king
  - rafiki
  - simba
  - holding up
  - presentation
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.418
    anchor_y: 0.105
    angle: 0.0
    scale_x: 0.097
    scale_y: 0.24
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.5
    anchor_y: 0.395
    angle: 0.0
    scale_x: 0.225
    scale_y: 0.495
    align: center
    start: 0.0
    stop: 1.0
example:
  - My new hobby
  - Me
