name: I Should Buy a Boat Cat
source: https://imgflip.com/meme/502024819/Surprised-Announcer
keywords:
  - cat
  - newspaper
  - suit
  - sophisticated cat
  - i should buy a boat
text:
  - style: upper
    color: black
    font: thick
    anchor_x: 0.05
    anchor_y: 0.05
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.75
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - I should buy a boat.
  - I should buy a boat.
