name: Spongebob reading two pages
source: https://imgflip.com/meme/347580183/Tony-discovers-a-new-element
keywords:
  - spongebob
  - book
  - cross-eyed
  - blue
  - red
  - choice
  - decision
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.738
    angle: 0.0
    scale_x: 0.488
    scale_y: 0.262
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.504
    anchor_y: 0.748
    angle: 0.0
    scale_x: 0.486
    scale_y: 0.252
    align: center
    start: 0.0
    stop: 1.0
example:
  - Option A
  - Option B
