name: Okay grandpa let's get you to bed
source: https://imgflip.com/meme/411364406/okay-grandpa-lets-get-you-to-bed
keywords:
  - grandpa
  - walker
  - elderly
  - sure grandpa let's get you to bed
  - old man
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.02
    angle: 0.0
    scale_x: 0.97
    scale_y: 0.16
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.83
    angle: 0.0
    scale_x: 0.97
    scale_y: 0.15
    align: center
    start: 0.0
    stop: 1.0
example:
  - "Back in my day, we owned the games we bought"
  - "Sure grandpa, let's get you to bed"
