name: Not that but this
source: https://imgflip.com/meme/132130031/Not-that-but-this
keywords:
  - drake
  - hotline bling
  - no
  - yes
  - rejection
  - approval
text:
  - style: upper
    color: black
    font: thick
    anchor_x: 0.51
    anchor_y: 0.01
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.48
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: black
    font: thick
    anchor_x: 0.51
    anchor_y: 0.51
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.48
    align: center
    start: 0.0
    stop: 1.0
example:
  - Using a complex tool
  - Writing a simple script
