name: Calculating Meme
source: https://imgflip.com/meme/92828109/Calculating-meme
keywords:
  - math lady
  - confused lady
  - calculating
  - thinking
  - equations
  - nazare tedesco
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.015
    anchor_y: 0.015
    angle: 0.0
    scale_x: 0.969
    scale_y: 0.135
    align: center
    start: 0.0
    stop: 1.0
example:
  - Me trying to calculate how many hours of sleep I will get if I fall asleep right now
