name: For the better right blank
source: https://imgflip.com/meme/321592868/For-the-better-right-blank
keywords:
  - anakin and padme
  - star wars
  - for the better right
  - four panels
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.38
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.11
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.51
    anchor_y: 0.38
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.11
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.88
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.11
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.51
    anchor_y: 0.88
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.11
    align: center
    start: 0.0
    stop: 1.0
example:
  - I'm going to change the world.
  - "For the better, right?"
  - ...
  - "For the better, right?"
