name: Finding Nemo Seagulls
source: https://imgflip.com/meme/43179458/Finding-Nemo-Seagulls
keywords:
  - finding nemo
  - seagulls
  - mine
  - birds
  - disney
  - pixar
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.003
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.147
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.85
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.13
    align: center
    start: 0.0
    stop: 1.0
example:
  - When someone opens a pack of gum in class
  - Mine? Mine? Mine?
