name: Jim Halpert Explains
source: https://imgflip.com/meme/228097860/Jim-Halpert-Explains
keywords:
  - the office
  - jim halpert
  - whiteboard
  - presentation
  - explaining
text:
  - style: upper
    color: black
    font: thick
    anchor_x: 0.015
    anchor_y: 0.04
    angle: 0.0
    scale_x: 0.62
    scale_y: 0.405
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: black
    font: thick
    anchor_x: 0.005
    anchor_y: 0.56
    angle: 0.0
    scale_x: 0.56
    scale_y: 0.365
    align: center
    start: 0.0
    stop: 1.0
example:
  - A simple explanation
  - The punchline or conclusion
