name: Assassination chain
source: https://imgflip.com/meme/204585338/Assassination-chain
keywords:
  - assassination chain
  - person of interest
  - sniper
  - gun pointing
  - church
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.3
    angle: 0.0
    scale_x: 0.3
    scale_y: 0.19
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.45
    anchor_y: 0.25
    angle: 0.0
    scale_x: 0.2
    scale_y: 0.18
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.7
    anchor_y: 0.22
    angle: 0.0
    scale_x: 0.2
    scale_y: 0.19
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.55
    anchor_y: 0.65
    angle: 0.0
    scale_x: 0.4
    scale_y: 0.33
    align: center
    start: 0.0
    stop: 1.0
example:
  - My high school self
  - College workload
  - Depression
  - My coping mechanisms
