name: My body is a machine
source: https://imgflip.com/meme/441502473/My-body-is-machine
keywords:
  - my body is a machine
  - that turns
  - into
  - skeleton
  - lifting weights
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.364
    anchor_y: 0.488
    angle: 0.0
    scale_x: 0.586
    scale_y: 0.112
    align: left
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.204
    anchor_y: 0.803
    angle: 0.0
    scale_x: 0.746
    scale_y: 0.102
    align: left
    start: 0.0
    stop: 1.0
example:
  - coffee
  - anxiety
