name: Blank Wild Pokemon Appears
source: https://imgflip.com/meme/216036135/Blank-Wild-Pokemon-Appears
keywords:
  - pokemon
  - wild pokemon
  - appeared
  - game boy
  - retro
text:
  - style: upper
    color: black
    font: thick
    anchor_x: 0.45
    anchor_y: 0.05
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.4
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: black
    font: thick
    anchor_x: 0.26
    anchor_y: 0.73
    angle: 0.0
    scale_x: 0.69
    scale_y: 0.105
    align: left
    start: 0.0
    stop: 1.0
example:
  - A healthy sleep schedule
  - RESPONSIBILITY
