name: Superior Royalty
source: https://imgflip.com/meme/275380114/Superior-Royalty
keywords:
  - superior royalty
  - volturi
  - twilight
  - aro
  - looking down
  - superiority
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.003
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.147
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.85
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.14
    align: center
    start: 0.0
    stop: 1.0
example:
  - PEOPLE WHO USE DARK MODE
  - PEOPLE WHO USE LIGHT MODE
