name: Aquamarine Whispering
source: https://imgflip.com/meme/330341559/Car-drives-off-of-cliffimproved
keywords:
  - girls whispering
  - jojo
  - emma roberts
  - secret
  - surprised
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.15
    anchor_y: 0.3
    angle: 0.0
    scale_x: 0.3
    scale_y: 0.3
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.48
    anchor_y: 0.25
    angle: 0.0
    scale_x: 0.27
    scale_y: 0.4
    align: center
    start: 0.0
    stop: 1.0
example:
  - Me telling a crazy story
  - My friend listening
