name: Absolute Cinema Blank
source: https://imgflip.com/meme/514151477/Absolute-Cinema-Blank
keywords:
  - martin scorsese
  - absolute cinema
  - director
  - hands up
  - black and white
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.02
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.13
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.85
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.13
    align: center
    start: 0.0
    stop: 1.0
example:
  - When the movie is actually good
  - Absolute Cinema
