name: Squidward Window
source: file://squidward-window.mp4
keywords:
  - squidward
  - window
  - looking
  - spongebob
  - jealous
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.035
    anchor_y: 0.01
    angle: 0.0
    scale_x: 0.44
    scale_y: 0.97
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: black
    font: thick
    anchor_x: 0.4
    anchor_y: 0.01
    angle: 0.0
    scale_x: 0.59
    scale_y: 0.82
    align: center
    start: 0.0
    stop: 1.0
example:
  - Me inside studying
  - Everyone else enjoying the weekend
