name: Are they in the room with us right now?
source: https://imgflip.com/meme/349549487/Are-they-in-the-room-with-us-right-now
keywords:
  - interrogation
  - psychiatrist
  - nikolas cruz
  - demon
  - pretending
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.026
    anchor_y: 0.258
    angle: 0.0
    scale_x: 0.389
    scale_y: 0.612
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.503
    anchor_y: 0.328
    angle: 0.0
    scale_x: 0.451
    scale_y: 0.582
    align: center
    start: 0.0
    stop: 1.0
example:
  - Therapist
  - Me pretending to hear voices
