name: Captain Phillips - I'm The Captain Now
source: https://imgflip.com/meme/Captain-Phillips-Im-The-Captain-Now
keywords:
  - captain phillips
  - im the captain now
  - look at me
  - somali pirate
  - tom hanks
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.015
    angle: 0.0
    scale_x: 0.97
    scale_y: 0.135
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.835
    angle: 0.0
    scale_x: 0.97
    scale_y: 0.15
    align: center
    start: 0.0
    stop: 1.0
example:
  - Look at me
  - I'm the captain now
