name: Blank Transparent Square
source: https://imgflip.com/meme/Blank-Transparent-Square
keywords:
  - blank
  - transparent
  - square
  - black
  - custom
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.05
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.75
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - TOP TEXT
  - BOTTOM TEXT
