name: Posted it again award
source: https://imgflip.com/meme/525022598/Posted-it-again-award
keywords:
  - clown
  - soldier
  - army
  - military
  - clown soldier
  - guys we are looking for
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.106
    anchor_y: 0.118
    angle: 0.0
    scale_x: 0.162
    scale_y: 0.594
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.188
    anchor_y: 0.078
    angle: 0.0
    scale_x: 0.24
    scale_y: 0.726
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.356
    anchor_y: 0.07
    angle: 0.0
    scale_x: 0.218
    scale_y: 0.744
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.534
    anchor_y: 0.022
    angle: 0.0
    scale_x: 0.348
    scale_y: 0.858
    align: center
    start: 0.0
    stop: 1.0
example:
  - Lurkers
  - My meme about a niche topic
  - The rest of the subreddit
  - Mods looking for rule breakers
