name: Darth Vader Where is Padme?
source: https://imgflip.com/meme/264138731/Darth-Vader-Where-is-Padme
keywords:
  - darth vader
  - where is padme
  - star wars
  - is she safe
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.005
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.015
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.08
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.015
    align: center
    start: 0.0
    stop: 1.0
example:
  - Where is Padme? Is she safe? Is she alright?
  - "It seems, in your anger, you killed her."
