name: For Dummies Book
source: https://imgflip.com/meme/131099891/For-dummies-book
keywords:
  - for dummies
  - book cover
  - yellow
  - reference
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.88
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.556
    anchor_y: 0.52
    angle: 0.0
    scale_x: 0.44
    scale_y: 0.24
    align: center
    start: 0.0
    stop: 1.0
example:
  - MEME MAKING
  - "It's easy!"
