name: Is This A Pigeon
source: https://imgflip.com/meme/137763318/Is-This-A-blank
keywords:
  - is this a pigeon
  - butterfly
  - anime
  - is this a
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.185
    angle: 0.0
    scale_x: 0.41
    scale_y: 0.665
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.73
    anchor_y: 0.09
    angle: 0.0
    scale_x: 0.21
    scale_y: 0.22
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.31
    anchor_y: 0.9
    angle: 0.0
    scale_x: 0.52
    scale_y: 0.07
    align: center
    start: 0.0
    stop: 1.0
example:
  - Me
  - A minor inconvenience
  - Is this a personal attack?
