name: Homer Simpson's Back Fat
source: https://imgflip.com/meme/157043617/Homer-Simpsons-Back-Fat
keywords:
  - homer simpson
  - back fat
  - the simpsons
  - hidden truth
  - expectation vs reality
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.23
    anchor_y: 0.188
    angle: 0.0
    scale_x: 0.25
    scale_y: 0.16
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.3
    anchor_y: 0.775
    angle: 0.0
    scale_x: 0.14
    scale_y: 0.175
    align: center
    start: 0.0
    stop: 1.0
example:
  - My resume
  - My actual skills
