name: Skeletor Until We Meet Again
source: https://imgflip.com/meme/335093314/Skeletor-until-we-meet-again
keywords:
  - skeletor
  - disturbing fact
  - until we meet again
  - he-man
  - running away
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.015
    anchor_y: 0.015
    angle: 0.0
    scale_x: 0.97
    scale_y: 0.205
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.015
    anchor_y: 0.85
    angle: 0.0
    scale_x: 0.97
    scale_y: 0.13
    align: center
    start: 0.0
    stop: 1.0
example:
  - Your dog only pretends to love you for food.
  - "Until we meet again!"
