name: Leonardo Dicaprio Cheers
source: https://imgflip.com/memetemplate/5496396
keywords:
  - leonardo dicaprio
  - cheers
  - great gatsby
  - toast
  - celebration
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.002
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.158
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.84
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.15
    align: center
    start: 0.0
    stop: 1.0
example:
  - HERE'S TO THE ONES
  - WHO ACTUALLY READ THE DOCUMENTATION
