name: Obama Medal
source: https://imgflip.com/meme/89853322/obama-medal
keywords:
  - obama
  - medal
  - barack obama
  - giving medal to himself
  - congratulating himself
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.15
    anchor_y: 0.3
    angle: 0.0
    scale_x: 0.25
    scale_y: 0.25
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.5
    anchor_y: 0.15
    angle: 0.0
    scale_x: 0.25
    scale_y: 0.25
    align: center
    start: 0.0
    stop: 1.0
example:
  - Me
  - Also me
