name: Bro Please Bro
source: https://imgflip.com/meme/258326835/Bro-Please-Bro
keywords:
  - bro please bro
  - different strain
  - indica
  - sativa
  - crying man
  - weed
  - joint
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.0
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.28
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.805
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.185
    align: center
    start: 0.0
    stop: 1.0
example:
  - bro please bro it's a different strain bro
  - this is indica not sativa bro please just try it
