name: Willem Dafoe Looking Up
source: https://imgflip.com/meme/489468779/Grr-emoji
keywords:
  - willem dafoe
  - looking up
  - at eternity's gate
  - scared
  - fear
  - god
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.13
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.15
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.72
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.15
    align: center
    start: 0.0
    stop: 1.0
example:
  - Me looking up at the giant spider on my ceiling
  - It has wings
