name: Skeletor Disturbing Facts
source: https://imgflip.com/meme/336049737/Skeletor-disturbing-facts
keywords:
  - skeletor
  - disturbing facts
  - until we meet again
  - he-man
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.01
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.34
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.85
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.13
    align: center
    start: 0.0
    stop: 1.0
example:
  - Your dog only pretends to love you for food.
  - "Until we meet again!"
