name: Mel Gibson explaining to Jesus
source: https://imgflip.com/meme/257865310/Dancing-monkeys
keywords:
  - mel gibson
  - jesus
  - explaining
  - passion of the christ
  - director
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.18
    anchor_y: 0.12
    angle: 0.0
    scale_x: 0.2
    scale_y: 0.24
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.52
    anchor_y: 0.06
    angle: 0.0
    scale_x: 0.2
    scale_y: 0.24
    align: center
    start: 0.0
    stop: 1.0
example:
  - Me explaining my 10-step plan to fix my life
  - My cat who just wants food
