name: Scared Cat
source: https://imgflip.com/meme/Scared-Cat
keywords:
  - scared cat
  - shocked cat
  - surprised cat
  - wide eyes
  - fear
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.015
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.195
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.79
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.195
    align: center
    start: 0.0
    stop: 1.0
example:
  - WHEN YOU HEAR A NOISE
  - AT 3 AM
