name: Telltale Will Remember That
source: https://imgflip.com/meme/229664299/telltale-will-remember-that
keywords:
  - telltale
  - will remember that
  - the walking dead
  - clementine
  - lee
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.02
    anchor_y: 0.02
    angle: 0.0
    scale_x: 0.96
    scale_y: 0.13
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.04
    angle: 0.0
    scale_x: 0.135
    scale_y: 0.04
    align: right
    start: 0.0
    stop: 1.0
example:
  - When you eat the last slice of pizza
  - Everyone
