name: I don't want to play with you anymore
source: https://imgflip.com/meme/196435636/I-dont-want-to-play-with-you-anymore
keywords:
  - toy story
  - andy
  - woody
  - dropping
  - discarding
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.5
    anchor_y: 0.356
    angle: 0.0
    scale_x: 0.22
    scale_y: 0.218
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.26
    anchor_y: 0.414
    angle: 0.0
    scale_x: 0.15
    scale_y: 0.204
    align: center
    start: 0.0
    stop: 1.0
example:
  - Me
  - My old hobby
