name: Morpheus Matrix Blue Pill Red Pill
source: https://imgflip.com/meme/183553656/morpheus-matrix-blue-pill-red-pill
keywords:
  - morpheus
  - matrix
  - blue pill
  - red pill
  - choice
  - laurence fishburne
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.1
    anchor_y: 0.02
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.13
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.08
    anchor_y: 0.55
    angle: 0.0
    scale_x: 0.24
    scale_y: 0.13
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.68
    anchor_y: 0.55
    angle: 0.0
    scale_x: 0.24
    scale_y: 0.13
    align: center
    start: 0.0
    stop: 1.0
example:
  - Choose your path
  - The painful truth
  - The blissful ignorance
