name: "Everywhere I go, I see his face"
source: https://imgflip.com/meme/394460955/Gunna-Fire-Writing
keywords:
  - spiderman
  - everywhere i go
  - i see his face
  - tony stark
  - iron man
  - marvel
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.21
    anchor_y: 0.492
    angle: 0.0
    scale_x: 0.506
    scale_y: 0.398
    align: center
    start: 0.0
    stop: 1.0
example:
  - shrek
