name: It's been 84 years
source: https://imgflip.com/meme/37687378/Its-been-84-years
keywords:
  - titanic
  - old lady
  - rose
  - waiting
  - long time
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.02
    anchor_y: 0.02
    angle: 0.0
    scale_x: 0.96
    scale_y: 0.23
    align: center
    start: 0.0
    stop: 1.0
example:
  - When the game update finally finishes downloading
