name: Expanding Brain
source: https://imgflip.com/memetemplate/93895088
keywords:
  - expanding brain
  - galaxy brain
  - four panels
  - intelligence
  - levels
text:
  - style: upper
    color: black
    font: thick
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 0.494
    scale_y: 0.248
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: black
    font: thick
    anchor_x: 0.0
    anchor_y: 0.251
    angle: 0.0
    scale_x: 0.494
    scale_y: 0.253
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: black
    font: thick
    anchor_x: 0.0
    anchor_y: 0.507
    angle: 0.0
    scale_x: 0.494
    scale_y: 0.227
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: black
    font: thick
    anchor_x: 0.0
    anchor_y: 0.742
    angle: 0.0
    scale_x: 0.494
    scale_y: 0.258
    align: center
    start: 0.0
    stop: 1.0
example:
  - "Using 'there', 'their', and 'they're' correctly"
  - Using 'whom' in a sentence
  - Using 'whomst' to sound smart
  - Using 'whomst'd've' in casual conversation
