name: Screaming Seagull
source: https://imgflip.com/meme/142945023/screaming-seagull
keywords:
  - screaming seagull
  - inhaling seagull
  - seagull
  - four panels
  - loud
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.02
    anchor_y: 0.02
    angle: 0.0
    scale_x: 0.46
    scale_y: 0.21
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.02
    anchor_y: 0.27
    angle: 0.0
    scale_x: 0.46
    scale_y: 0.21
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.02
    anchor_y: 0.52
    angle: 0.0
    scale_x: 0.46
    scale_y: 0.21
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.02
    anchor_y: 0.77
    angle: 0.0
    scale_x: 0.46
    scale_y: 0.19
    align: center
    start: 0.0
    stop: 1.0
example:
  - When you're trying to be quiet
  - But then you stub your toe
  - Inhales...
  - AHHHHHHHHHHH
