name: Limmy Waking Up
source: https://imgflip.com/meme/260948664/Typing-kitty
keywords:
  - limmy
  - waking up
  - in bed
  - confused
  - disgusted
  - reaction
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.002
    angle: 0.0
    scale_x: 0.978
    scale_y: 0.148
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.85
    angle: 0.0
    scale_x: 0.978
    scale_y: 0.14
    align: center
    start: 0.0
    stop: 1.0
example:
  - When you wake up at 3 AM and remember something embarrassing you did in 2012
  - Why did I say that
