name: A Train School Bus
source: file://a-train-school-bus.mp4
keywords:
  - school bus
  - train
  - collision
  - accident
  - incoming
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.356
    angle: 0.0
    scale_x: 0.33
    scale_y: 0.088
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.64
    anchor_y: 0.392
    angle: 0.0
    scale_x: 0.215
    scale_y: 0.156
    align: center
    start: 0.0
    stop: 1.0
example:
  - My plans for the weekend
  - Monday morning
