name: Patrick Not My Wallet
source: https://imgflip.com/meme/109894751/patrick-not-my-wallet
keywords:
  - patrick
  - not my wallet
  - man ray
  - spongebob
  - multi-panel
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.18
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.065
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.51
    anchor_y: 0.18
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.065
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.43
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.065
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.51
    anchor_y: 0.43
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.065
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.69
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.065
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.51
    anchor_y: 0.69
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.065
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.94
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.055
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.51
    anchor_y: 0.94
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.055
    align: center
    start: 0.0
    stop: 1.0
example:
  - Is this your ID?
  - Yep.
  - And this is your name on it?
  - Yep.
  - So this must be your wallet.
  - Then take it.
  - It's not my wallet.
  - "You dimwit!"
