name: Madness - This is Sparta
source: https://imgflip.com/meme/1650385/madness---this-is-sparta
keywords:
  - this is sparta
  - leonidas
  - kick
  - 300
  - pit
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.201
    anchor_y: 0.127
    angle: 0.0
    scale_x: 0.347
    scale_y: 0.753
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.498
    anchor_y: 0.104
    angle: 0.0
    scale_x: 0.272
    scale_y: 0.764
    align: center
    start: 0.0
    stop: 1.0
example:
  - Me
  - My responsibilities
