name: A center for ants?
source: https://imgflip.com/meme/6463210/A-center-for-ants
keywords:
  - zoolander
  - derek zoolander
  - what is this
  - center for ants
  - ben stiller
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.005
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.245
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.75
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.24
    align: center
    start: 0.0
    stop: 1.0
example:
  - WHAT IS THIS? A CENTER FOR ANTS?
  - "IT NEEDS TO BE AT LEAST... THREE TIMES BIGGER THAN THIS!"
