name: Steve Buscemi Fellow Kids
source: https://imgflip.com/meme/58910635/Steve-Buscemi-Fellow-Kids
keywords:
  - how do you do fellow kids
  - steve buscemi
  - music band
  - skateboard
  - fellow kids
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.002
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.148
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.84
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.15
    align: center
    start: 0.0
    stop: 1.0
example:
  - "HOW DO YOU DO, FELLOW KIDS?"
  - ME TRYING TO FIT IN WITH THE GEN Z COWORKERS
