name: Spongebob Burning Paper
source: https://imgflip.com/meme/139971723/Spongebob-Burning-Paper
keywords:
  - spongebob
  - burning paper
  - fire
  - opinion
  - throw in fire
  - four panels
text:
  - style: upper
    color: black
    font: thick
    anchor_x: 0.08
    anchor_y: 0.065
    angle: 0.0
    scale_x: 0.308
    scale_y: 0.353
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: black
    font: thick
    anchor_x: 0.514
    anchor_y: 0.236
    angle: 0.0
    scale_x: 0.174
    scale_y: 0.15
    align: center
    start: 0.0
    stop: 1.0
example:
  - unpopular opinion
  - unpopular opinion
