name: Leave Britney Alone
source: https://imgflip.com/meme/7343489/Leave-Britney-Alone
keywords:
  - leave britney alone
  - chris crocker
  - crying
  - blonde
  - emotional
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.003
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.177
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.81
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.18
    align: center
    start: 0.0
    stop: 1.0
example:
  - LEAVE BRITNEY
  - "ALONE!"
