name: Cat looks inside
source: https://imgflip.com/meme/453425234/Cat-looks-inside
keywords:
  - cat
  - staring
  - close up
  - pov
  - looking down
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.01
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.15
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.84
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.15
    align: center
    start: 0.0
    stop: 1.0
example:
  - me looking into the microwave
  - waiting for my food to heat up
