name: Patrick Dunking Meme
source: https://imgflip.com/meme/403946102/Patrick-Dunk-Meme
keywords:
  - patrick star
  - spongebob
  - basketball
  - dunk
  - lebron and wade
  - celebration
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.205
    anchor_y: 0.258
    angle: 0.0
    scale_x: 0.22
    scale_y: 0.34
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.498
    anchor_y: 0.382
    angle: 0.0
    scale_x: 0.4
    scale_y: 0.576
    align: center
    start: 0.0
    stop: 1.0
example:
  - My group partner who did all the work
  - Me presenting the project
