name: Traumatized Mr. Incredible
source: https://imgflip.com/meme/340157305/Traumatized-Mr-Incredible
keywords:
  - traumatized mr incredible
  - uncanny mr incredible
  - people who know
  - people who don't know
  - mr incredible becoming uncanny
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.01
    angle: 0.0
    scale_x: 0.47
    scale_y: 0.19
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.52
    anchor_y: 0.01
    angle: 0.0
    scale_x: 0.47
    scale_y: 0.19
    align: center
    start: 0.0
    stop: 1.0
example:
  - People who don't know
  - People who know
