name: Bad Pun Dog
source: https://imgflip.com/meme/Bad-Pun-Dog
keywords:
  - bad pun dog
  - husky
  - joke
  - three panels
  - pun
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.02
    anchor_y: 0.02
    angle: 0.0
    scale_x: 0.96
    scale_y: 0.1
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.02
    anchor_y: 0.32
    angle: 0.0
    scale_x: 0.96
    scale_y: 0.1
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.02
    anchor_y: 0.58
    angle: 0.0
    scale_x: 0.96
    scale_y: 0.1
    align: center
    start: 0.0
    stop: 1.0
example:
  - What do you call a fake noodle?
  - "An impasta!"
  - "Get it?!"
