name: What kind of American
source: https://imgflip.com/meme/499301001/What-kind-of-American
keywords:
  - civil war
  - jesse plemons
  - what kind of american
  - soldier
  - red sunglasses
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.005
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.145
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.85
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.135
    align: center
    start: 0.0
    stop: 1.0
example:
  - What kind of...
  - ...American are you?
