name: Leonardo DiCaprio Pointing
source: https://imgflip.com/meme/234856740/Leonardo-DiCaprio-Pointing
keywords:
  - leonardo dicaprio
  - pointing
  - once upon a time in hollywood
  - rick dalton
  - tv
  - couch
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.02
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.18
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.8
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.18
    align: center
    start: 0.0
    stop: 1.0
example:
  - Me when I see the actor from that one movie
  - "Look! That's him!"
