name: Types of Headaches
source: https://imgflip.com/memetemplate/119215120
keywords:
  - types of headaches
  - migraine
  - hypertension
  - stress
  - red head
text:
  - style: upper
    color: black
    font: thick
    anchor_x: 0.07
    anchor_y: 0.01
    angle: 0.0
    scale_x: 0.87
    scale_y: 0.138
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: black
    font: thick
    anchor_x: 0.5
    anchor_y: 0.63
    angle: 0.0
    scale_x: 0.44
    scale_y: 0.08
    align: center
    start: 0.0
    stop: 1.0
example:
  - Types of Headaches
  - Talking to flat earthers
