name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test
      
      - name: Validate app configurations
        run: |
          echo "Checking all app configurations..."
          for app in apps/*/; do
            if [ -d "$app" ]; then
              app_name=$(basename "$app")
              echo "Validating $app_name..."
              
              # Check required files exist
              for file in "config.json" "docker-compose.json" "metadata/description.md" "metadata/logo.jpg"; do
                if [ ! -f "$app$file" ]; then
                  echo "❌ Missing required file: $app$file"
                  exit 1
                fi
              done
              
              # Validate JSON files
              if ! jq empty "$app/config.json" 2>/dev/null; then
                echo "❌ Invalid JSON in $app/config.json"
                exit 1
              fi
              
              if ! jq empty "$app/docker-compose.json" 2>/dev/null; then
                echo "❌ Invalid JSON in $app/docker-compose.json"
                exit 1
              fi
              
              echo "✅ $app_name validated successfully"
            fi
          done
          echo "All apps validated successfully!"
