name: Track AIPAC
source: https://imgflip.com/meme/619448663/Aipac
keywords:
  - aipac
  - track aipac
  - politician
  - funding
  - lobby
  - israel
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.538
    anchor_y: 0.328
    angle: 0.0
    scale_x: 0.38
    scale_y: 0.33
    align: left
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.276
    angle: 0.0
    scale_x: 0.508
    scale_y: 0.714
    align: center
    start: 0.0
    stop: 1.0
example:
  - "$1,000,000"
  - Politician Name
